/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.ucr.IF3000.BiblioTech.Interface;

import File.RequestAudioVisualFile;
import cr.ac.ucr.IF3000.BiblioTech.domain.RequestAudioVisual;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Emmanuel
 */
public class ListOfLoanAudiovisuals extends javax.swing.JFrame {

    /**
     * Creates new form ListOfLoanAudiovisuals
     */
    public ListOfLoanAudiovisuals() {
        initComponents();
        try {
            showTable(lvl_loanAudioVisuals);
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_BackBooksRecord = new javax.swing.JButton();
        lbl_InfoListAudiovisuals = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lvl_loanAudioVisuals = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_BackBooksRecord.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_BackBooksRecord.setText("Back");
        btn_BackBooksRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackBooksRecordActionPerformed(evt);
            }
        });

        lbl_InfoListAudiovisuals.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lbl_InfoListAudiovisuals.setText("Loan Audiovisuals");

        lvl_loanAudioVisuals.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Student", "Date of removing book", "Date of delivery book", "Equitment name", "Brand"
            }
        ));
        jScrollPane1.setViewportView(lvl_loanAudioVisuals);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btn_BackBooksRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_InfoListAudiovisuals, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_InfoListAudiovisuals, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_BackBooksRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showTable(JTable table) throws IOException {
        RequestAudioVisualFile audioFile = new RequestAudioVisualFile();
        RequestAudioVisual audioTemp;
        ArrayList<RequestAudioVisual> myArrayList = audioFile.getLoanList();
        DefaultTableModel modelo = (DefaultTableModel) table.getModel();
        table = new JTable(modelo);
        for(int i=0;i<myArrayList.size();i++){
            audioTemp = myArrayList.get(i);
            Object obj[] = new Object[]{
                audioTemp.getId_card(), audioTemp.getDate_remove(), audioTemp.getDate_delivery(), audioTemp.getName(), audioTemp.getBrand()
            };
            modelo.addRow(obj);
        }
        
        table.setModel(modelo);
    }
    
    private void btn_BackBooksRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackBooksRecordActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_BackBooksRecordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListOfLoanAudiovisuals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListOfLoanAudiovisuals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListOfLoanAudiovisuals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListOfLoanAudiovisuals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListOfLoanAudiovisuals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BackBooksRecord;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_InfoListAudiovisuals;
    private javax.swing.JTable lvl_loanAudioVisuals;
    // End of variables declaration//GEN-END:variables
}
