/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.ucr.IF3000.BiblioTech.Interface;

import com.mxrck.autocompleter.TextAutoCompleter;
import cr.ac.ucr.IF3000.BiblioTech.domain.AudioVisual;
import cr.ac.ucr.IF3000.BiblioTech.domain.Books;
import cr.ac.ucr.IF3000.BiblioTech.domain.RequestAudioVisual;
import cr.ac.ucr.IF3000.BiblioTech.domain.RequestBook;
import File.AudioVisualFile;
import File.BooksFile;
import File.RequestAudioVisualFile;
import File.RequestBookFile;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;

/**
 *
 * @author Emmanuel
 */
public class LoanAudioVisual extends javax.swing.JFrame {

    /**
     * Creates new form LoanAudioBook
     */
    public LoanAudioVisual() {
        initComponents();
        try {
            autoComplete();
        } catch (IOException e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_removing = new javax.swing.JLabel();
        lbl_delivery = new javax.swing.JLabel();
        lbl_titleloanAudio = new javax.swing.JLabel();
        btn_loan = new javax.swing.JButton();
        tfd_search = new javax.swing.JTextField();
        lbl_search = new javax.swing.JLabel();
        lbl_audio = new javax.swing.JLabel();
        tfd_audio = new javax.swing.JTextField();
        jd_removing = new com.toedter.calendar.JDateChooser();
        jd_delivery = new com.toedter.calendar.JDateChooser();
        btn_BackSearchStudent = new javax.swing.JButton();
        lbl_idStudent = new javax.swing.JLabel();
        tfd_idStudent = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_removing.setText("Date of removing audiovisual");

        lbl_delivery.setText("Date of delivey audiovisual");

        lbl_titleloanAudio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_titleloanAudio.setText("Loan Audiovisual");

        btn_loan.setText("Request loan");
        btn_loan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loanActionPerformed(evt);
            }
        });

        tfd_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfd_searchKeyTyped(evt);
            }
        });

        lbl_search.setText("Search audiovisual for code or title");

        lbl_audio.setText("AudioVisual");

        tfd_audio.setEditable(false);

        btn_BackSearchStudent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_BackSearchStudent.setText("Back");
        btn_BackSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackSearchStudentActionPerformed(evt);
            }
        });

        lbl_idStudent.setText("Id student:");

        tfd_idStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_idStudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_removing)
                    .addComponent(lbl_delivery))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jd_removing, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                    .addComponent(jd_delivery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(192, 192, 192))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(313, 313, 313)
                        .addComponent(lbl_titleloanAudio))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(btn_BackSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)
                        .addComponent(btn_loan))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(tfd_search, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(190, 190, 190)
                                .addComponent(lbl_audio)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfd_audio, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(lbl_search)
                                .addGap(271, 271, 271)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl_idStudent)
                                .addGap(184, 184, 184))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(tfd_idStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_titleloanAudio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfd_idStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_idStudent))
                .addGap(18, 18, 18)
                .addComponent(lbl_search)
                .addGap(18, 18, 18)
                .addComponent(tfd_search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_audio)
                    .addComponent(tfd_audio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_removing)
                    .addComponent(jd_removing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_delivery)
                    .addComponent(jd_delivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_loan)
                    .addComponent(btn_BackSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //texfield autocomplete
    public void autoComplete() throws IOException{
        TextAutoCompleter complete = new TextAutoCompleter(tfd_search);
        File file = new File("./AudioVisual.dat");
        AudioVisualFile audioFile = new AudioVisualFile(file);
        ArrayList<AudioVisual> myArrayList = audioFile.getAudioList();
        AudioVisual audioTemp = new AudioVisual();
        for(int i= 0;i<myArrayList.size();i++){
            audioTemp = myArrayList.get(i);
            complete.addItem(audioTemp.getName());
            complete.addItem(audioTemp.getCode());
        }
    }//end method
    //method to save the loan audiovisual
    public void insertAudioVisual(){
        try {
            File file = new File("./AudioVisual.dat");
            AudioVisualFile audioFile = new AudioVisualFile(file);
            ArrayList<AudioVisual> myArrayList = audioFile.getAudioList();
            AudioVisual audioTemp = new AudioVisual();
            for(int i= 0;i<myArrayList.size();i++){
                if(myArrayList.get(i).getName().equals(tfd_audio.getText()))
                    audioTemp = myArrayList.get(i);
            }
            if(audioTemp == null){
                System.err.println("The audio visual couldn't be found in the file");
            }else{
                SearchStudent get_id = new SearchStudent();
                RequestAudioVisualFile loanAudio = new RequestAudioVisualFile();
                String card_Student = tfd_idStudent.getText();
                String formato = "dd/MM/yyyy";
                Date date1 = jd_removing.getDate();
                Date date2 = jd_delivery.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat(formato);
                String date_removing = sdf.format(date1);
                String date_delivery = sdf.format(date2);
                String titleAudio = tfd_audio.getText();
                String brand= audioTemp.getBrand();
                int amount = audioTemp.getAmount();
                ArrayList<RequestAudioVisual> listLoan = loanAudio.getLoanList();
                int available = 0;
                if(listLoan.size()>0){
                    for(int c=0;c<listLoan.size();c++){
                        if(listLoan.get(c).getName().equals(titleAudio)){
                            available = listLoan.get(c).getAvailable()-1;
                        }
                    }
                }else{
                    available = audioTemp.getAmount()-1;
                }
                RequestAudioVisual rAudioVisual = new RequestAudioVisual(card_Student, available, date_removing, date_delivery, titleAudio, brand, audioTemp.getModel(), audioTemp.getCode(), amount);
                if(available>=0){
                    loanAudio.insertLoanAudio(rAudioVisual);
                }
                else{
                    System.err.println("Don´t found audio visual available");
                }
                tfd_search.setText("");
                tfd_audio.setText("");
                jd_removing.setDateFormatString("");
                jd_delivery.setDateFormatString("");
                tfd_search.requestFocus();
            }
        } catch (IOException e) {
        }
    }
    
    private void tfd_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfd_searchKeyTyped
        String titleAudio = tfd_search.getText();
        String audio = "";
        try {
            File file = new File("./AudioVisual.dat");
            AudioVisualFile audioFile = new AudioVisualFile(file);
            ArrayList<AudioVisual> listOfAudio = audioFile.getAudioList();
            for(int i=0;i<listOfAudio.size();i++){
                String code= ""+listOfAudio.get(i).getCode();
                if(code.equals(titleAudio)){
                    audio=listOfAudio.get(i).getName();
                }else if(listOfAudio.get(i).getName().equals(titleAudio)){
                    audio=listOfAudio.get(i).getName();
                }
            }
        } catch (IOException e) {
        }
        
        tfd_audio.setText(audio);
    }//GEN-LAST:event_tfd_searchKeyTyped

    private void btn_loanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loanActionPerformed
        if(!tfd_idStudent.getText().equals("") || !jd_removing.getDate().toString().equals("") || !jd_delivery.getDate().toString().equals("")){
            insertAudioVisual();
        }
    }//GEN-LAST:event_btn_loanActionPerformed

    private void btn_BackSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackSearchStudentActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_BackSearchStudentActionPerformed

    private void tfd_idStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_idStudentActionPerformed

    }//GEN-LAST:event_tfd_idStudentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanAudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanAudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanAudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanAudioVisual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanAudioVisual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BackSearchStudent;
    private javax.swing.JButton btn_loan;
    private com.toedter.calendar.JDateChooser jd_delivery;
    private com.toedter.calendar.JDateChooser jd_removing;
    private javax.swing.JLabel lbl_audio;
    private javax.swing.JLabel lbl_delivery;
    private javax.swing.JLabel lbl_idStudent;
    private javax.swing.JLabel lbl_removing;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JLabel lbl_titleloanAudio;
    private javax.swing.JTextField tfd_audio;
    private javax.swing.JTextField tfd_idStudent;
    private javax.swing.JTextField tfd_search;
    // End of variables declaration//GEN-END:variables
}
