/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cr.ac.ucr.IF3000.BiblioTech.Interface;

import com.mxrck.autocompleter.TextAutoCompleter;
import File.BooksFile;
import cr.ac.ucr.IF3000.BiblioTech.domain.Books;
import cr.ac.ucr.IF3000.BiblioTech.domain.RequestBook;
import cr.ac.ucr.IF3000.BiblioTech.domain.Student;
import File.RequestBookFile;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;


/**
 *
 * @author Emmanuel
 */
public class LoanBooks extends javax.swing.JFrame {

    /**
     * Creates new form LoanBooks
     */
    public LoanBooks() {
        initComponents();
        try {
            autoComplete();
        } catch (IOException e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_titleloanBooks = new javax.swing.JLabel();
        jd_removing = new com.toedter.calendar.JDateChooser();
        jd_delivery = new com.toedter.calendar.JDateChooser();
        lbl_removing = new javax.swing.JLabel();
        lbl_delivery = new javax.swing.JLabel();
        btn_loan = new javax.swing.JButton();
        lbl_search = new javax.swing.JLabel();
        lbl_book = new javax.swing.JLabel();
        tfd_book = new javax.swing.JTextField();
        tfd_search = new javax.swing.JTextField();
        btn_BackSearchStudent = new javax.swing.JButton();
        tfd_idStudent = new javax.swing.JTextField();
        lbl_idStudent = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        lbl_titleloanBooks.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_titleloanBooks.setText("Loan Book");

        lbl_removing.setText("Date of removing book");

        lbl_delivery.setText("Date of delivey book");

        btn_loan.setText("Request loan");
        btn_loan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loanActionPerformed(evt);
            }
        });

        lbl_search.setText("Search book for code or title");

        lbl_book.setText("Book");

        tfd_book.setEditable(false);

        tfd_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfd_searchKeyTyped(evt);
            }
        });

        btn_BackSearchStudent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_BackSearchStudent.setText("Back");
        btn_BackSearchStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackSearchStudentActionPerformed(evt);
            }
        });

        tfd_idStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfd_idStudentActionPerformed(evt);
            }
        });

        lbl_idStudent.setText("Id student:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_removing)
                    .addComponent(lbl_delivery))
                .addGap(67, 67, 67)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jd_removing, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(jd_delivery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(198, 198, 198))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btn_BackSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_loan)
                .addGap(292, 292, 292))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(313, 313, 313)
                                .addComponent(lbl_titleloanBooks))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(175, 175, 175)
                                .addComponent(lbl_idStudent)))
                        .addGap(184, 184, 184))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbl_search)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(138, 138, 138)
                                    .addComponent(tfd_idStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(tfd_search, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_book)
                                .addGap(35, 35, 35)
                                .addComponent(tfd_book, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_BackSearchStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_titleloanBooks)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tfd_idStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_idStudent))
                                        .addGap(33, 33, 33)
                                        .addComponent(lbl_search)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfd_search, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(tfd_book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lbl_book))
                                        .addGap(28, 28, 28)
                                        .addComponent(jd_removing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lbl_removing))
                                .addGap(63, 63, 63)
                                .addComponent(jd_delivery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_delivery))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(btn_loan)))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void insertLoan(){
        try {
            File file = new File("./Books.dat");
            BooksFile bookFile = new BooksFile(file);
            ArrayList<Books> myArrayList = bookFile.getBooksList();
            Books bookTemp = new Books();
            for(int i= 0;i<myArrayList.size();i++){
                if(myArrayList.get(i).getTitle().equals(tfd_book.getText()))
                    bookTemp = myArrayList.get(i);
            }
            if(bookTemp == null){
                System.err.println("The book couldn't be found in the file");
            }else{
                RequestBookFile loanBook = new RequestBookFile();
                String formato = "dd/MM/yyyy";
                String card_student = tfd_idStudent.getText();
                Date date1 = jd_removing.getDate();
                Date date2 = jd_delivery.getDate();
                SimpleDateFormat sdf = new SimpleDateFormat(formato);
                String date_removing = sdf.format(date1);
                String date_delivery = sdf.format(date2);
                String titleBook = tfd_book.getText();
                String authors= bookTemp.getAuthors();
                int amount = bookTemp.getAmount();
                ArrayList<RequestBook> listLoan = loanBook.getLoanList();
                int available = 0;
                if(listLoan.size()>0){
                    for(int c=0;c<listLoan.size();c++){
                        if(listLoan.get(c).getTitle().equals(titleBook)){
                            available = listLoan.get(c).getAvailable()-1;
                        }
                    }
                }else{
                    available = bookTemp.getAmount()-1;
                }
                RequestBook rBook = new RequestBook(card_student, available, date_removing, date_delivery, titleBook, authors, bookTemp.getType(), bookTemp.getCode(), amount, bookTemp.getAge());
                if(available>=0){
                    loanBook.insertLoanBook(rBook);
                }
                else{
                    System.err.println("Don´t found book available");
                }
                tfd_search.setText("");
                tfd_book.setText("");
                jd_removing.setDateFormatString("");
                jd_delivery.setDateFormatString("");
                tfd_search.requestFocus();
            }
        } catch (Exception e) {
        }
    }
    
    private void tfd_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfd_searchKeyTyped
        String titleBook = tfd_search.getText();
        String book = "";
        try {
            File file = new File("./Books.dat");
            BooksFile bookFile = new BooksFile(file);
            ArrayList<Books> listOfBook = bookFile.getBooksList();
            for(int i=0;i<listOfBook.size();i++){
                if(listOfBook.get(i).getCode().equals(titleBook)){
                    book=listOfBook.get(i).getTitle();
                }else if(listOfBook.get(i).getTitle().equals(titleBook)){
                    book=listOfBook.get(i).getTitle();
                }
            }
        } catch (IOException e) {
        }
        
        tfd_book.setText(book);
          
    }//GEN-LAST:event_tfd_searchKeyTyped

    private void btn_loanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loanActionPerformed
        if(!tfd_idStudent.getText().equals("") || !jd_removing.getDate().toString().equals("") || !jd_delivery.getDate().toString().equals("")){
            insertLoan();
        }
        
    }//GEN-LAST:event_btn_loanActionPerformed

    private void btn_BackSearchStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackSearchStudentActionPerformed
        // TODO add your handling code here:
        Principal p = new Principal();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_BackSearchStudentActionPerformed

    private void tfd_idStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfd_idStudentActionPerformed
        
    }//GEN-LAST:event_tfd_idStudentActionPerformed

    public void autoComplete() throws IOException{
        TextAutoCompleter complete = new TextAutoCompleter(tfd_search);
        File file = new File("./Books.dat");
        BooksFile bookFile = new BooksFile(file);
        ArrayList<Books> myArrayList = bookFile.getBooksList();
        Books bookTemp = new Books();
        for(int i= 0;i<myArrayList.size();i++){
            bookTemp = myArrayList.get(i);
            complete.addItem(bookTemp.getTitle());
            complete.addItem(bookTemp.getCode());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanBooks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanBooks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_BackSearchStudent;
    private javax.swing.JButton btn_loan;
    private com.toedter.calendar.JDateChooser jd_delivery;
    private com.toedter.calendar.JDateChooser jd_removing;
    private javax.swing.JLabel lbl_book;
    private javax.swing.JLabel lbl_delivery;
    private javax.swing.JLabel lbl_idStudent;
    private javax.swing.JLabel lbl_removing;
    private javax.swing.JLabel lbl_search;
    private javax.swing.JLabel lbl_titleloanBooks;
    private javax.swing.JTextField tfd_book;
    private javax.swing.JTextField tfd_idStudent;
    private javax.swing.JTextField tfd_search;
    // End of variables declaration//GEN-END:variables
}
